#include <AAFTypeDefUIDs.h>
#include <AAFDataDefs.h>
#include <AAFCodecDefs.h>
#include <AAFContainerDefs.h>
#include <AAFCompressionDefs.h>
#include <AAFExtEnum.h>
#include <AAFInterpolatorDefs.h>
#include <AAFTypes.h>
#include <AAFEssenceFormats.h>
#include <map>
#include <string>

std::map<std::string, aafUID_t> get_typedef_map()
{
    std::map<std::string, aafUID_t> def_map;
    #define MAP_ADD( NAME ) def_map[ #NAME ] = NAME;
    MAP_ADD(kAAFTypeID_UInt8)
    MAP_ADD(kAAFTypeID_UInt16)
    MAP_ADD(kAAFTypeID_UInt32)
    MAP_ADD(kAAFTypeID_UInt64)
    MAP_ADD(kAAFTypeID_Int8)
    MAP_ADD(kAAFTypeID_Int16)
    MAP_ADD(kAAFTypeID_Int32)
    MAP_ADD(kAAFTypeID_Int64)
    MAP_ADD(kAAFTypeID_PositionType)
    MAP_ADD(kAAFTypeID_LengthType)
    MAP_ADD(kAAFTypeID_JPEGTableIDType)
    MAP_ADD(kAAFTypeID_PhaseFrameType)
    MAP_ADD(kAAFTypeID_AUID)
    MAP_ADD(kAAFTypeID_MobIDType)
    MAP_ADD(kAAFTypeID_Boolean)
    MAP_ADD(kAAFTypeID_Character)
    MAP_ADD(kAAFTypeID_String)
    MAP_ADD(kAAFTypeID_ProductReleaseType)
    MAP_ADD(kAAFTypeID_TapeFormatType)
    MAP_ADD(kAAFTypeID_VideoSignalType)
    MAP_ADD(kAAFTypeID_TapeCaseType)
    MAP_ADD(kAAFTypeID_ColorSitingType)
    MAP_ADD(kAAFTypeID_EditHintType)
    MAP_ADD(kAAFTypeID_FadeType)
    MAP_ADD(kAAFTypeID_LayoutType)
    MAP_ADD(kAAFTypeID_TCSource)
    MAP_ADD(kAAFTypeID_PulldownDirectionType)
    MAP_ADD(kAAFTypeID_PulldownKindType)
    MAP_ADD(kAAFTypeID_EdgeType)
    MAP_ADD(kAAFTypeID_FilmType)
    MAP_ADD(kAAFTypeID_RGBAComponentKind)
    MAP_ADD(kAAFTypeID_ReferenceType)
    MAP_ADD(kAAFTypeID_AlphaTransparencyType)
    MAP_ADD(kAAFTypeID_FieldNumber)
    MAP_ADD(kAAFTypeID_ElectroSpatialFormulation)
    MAP_ADD(kAAFTypeID_EmphasisType)
    MAP_ADD(kAAFTypeID_AuxBitsModeType)
    MAP_ADD(kAAFTypeID_ChannelStatusModeType)
    MAP_ADD(kAAFTypeID_UserDataModeType)
    MAP_ADD(kAAFTypeID_SignalStandardType)
    MAP_ADD(kAAFTypeID_ScanningDirectionType)
    MAP_ADD(kAAFTypeID_ContentScanningType)
    MAP_ADD(kAAFTypeID_TitleAlignmentType)
    MAP_ADD(kAAFTypeID_OperationCategoryType)
    MAP_ADD(kAAFTypeID_TransferCharacteristicType)
    MAP_ADD(kAAFTypeID_PluginCategoryType)
    MAP_ADD(kAAFTypeID_UsageType)
    MAP_ADD(kAAFTypeID_ColorPrimariesType)
    MAP_ADD(kAAFTypeID_CodingEquationsType)
    MAP_ADD(kAAFTypeID_Rational)
    MAP_ADD(kAAFTypeID_ProductVersion)
    MAP_ADD(kAAFTypeID_VersionType)
    MAP_ADD(kAAFTypeID_RGBAComponent)
    MAP_ADD(kAAFTypeID_DateStruct)
    MAP_ADD(kAAFTypeID_TimeStruct)
    MAP_ADD(kAAFTypeID_TimeStamp)
    MAP_ADD(kAAFTypeID_UInt8Array)
    MAP_ADD(kAAFTypeID_UInt8Array12)
    MAP_ADD(kAAFTypeID_Int32Array)
    MAP_ADD(kAAFTypeID_Int64Array)
    MAP_ADD(kAAFTypeID_StringArray)
    MAP_ADD(kAAFTypeID_AUIDArray)
    MAP_ADD(kAAFTypeID_PositionArray)
    MAP_ADD(kAAFTypeID_UInt8Array8)
    MAP_ADD(kAAFTypeID_UInt32Array)
    MAP_ADD(kAAFTypeID_ChannelStatusModeArray)
    MAP_ADD(kAAFTypeID_UserDataModeArray)
    MAP_ADD(kAAFTypeID_RGBALayout)
    MAP_ADD(kAAFTypeID_AUIDSet)
    MAP_ADD(kAAFTypeID_UInt32Set)
    MAP_ADD(kAAFTypeID_DataValue)
    MAP_ADD(kAAFTypeID_Stream)
    MAP_ADD(kAAFTypeID_Indirect)
    MAP_ADD(kAAFTypeID_Opaque)
    MAP_ADD(kAAFTypeID_ClassDefinitionWeakReference)
    MAP_ADD(kAAFTypeID_ContainerDefinitionWeakReference)
    MAP_ADD(kAAFTypeID_DataDefinitionWeakReference)
    MAP_ADD(kAAFTypeID_InterpolationDefinitionWeakReference)
    MAP_ADD(kAAFTypeID_MobWeakReference)
    MAP_ADD(kAAFTypeID_OperationDefinitionWeakReference)
    MAP_ADD(kAAFTypeID_ParameterDefinitionWeakReference)
    MAP_ADD(kAAFTypeID_TypeDefinitionWeakReference)
    MAP_ADD(kAAFTypeID_PluginDefinitionWeakReference)
    MAP_ADD(kAAFTypeID_CodecDefinitionWeakReference)
    MAP_ADD(kAAFTypeID_PropertyDefinitionWeakReference)
    MAP_ADD(kAAFTypeID_ContentStorageStrongReference)
    MAP_ADD(kAAFTypeID_DictionaryStrongReference)
    MAP_ADD(kAAFTypeID_EssenceDescriptorStrongReference)
    MAP_ADD(kAAFTypeID_NetworkLocatorStrongReference)
    MAP_ADD(kAAFTypeID_OperationGroupStrongReference)
    MAP_ADD(kAAFTypeID_SegmentStrongReference)
    MAP_ADD(kAAFTypeID_SourceClipStrongReference)
    MAP_ADD(kAAFTypeID_SourceReferenceStrongReference)
    MAP_ADD(kAAFTypeID_ClassDefinitionStrongReference)
    MAP_ADD(kAAFTypeID_CodecDefinitionStrongReference)
    MAP_ADD(kAAFTypeID_ComponentStrongReference)
    MAP_ADD(kAAFTypeID_ContainerDefinitionStrongReference)
    MAP_ADD(kAAFTypeID_ControlPointStrongReference)
    MAP_ADD(kAAFTypeID_DataDefinitionStrongReference)
    MAP_ADD(kAAFTypeID_EssenceDataStrongReference)
    MAP_ADD(kAAFTypeID_IdentificationStrongReference)
    MAP_ADD(kAAFTypeID_InterpolationDefinitionStrongReference)
    MAP_ADD(kAAFTypeID_LocatorStrongReference)
    MAP_ADD(kAAFTypeID_MobStrongReference)
    MAP_ADD(kAAFTypeID_MobSlotStrongReference)
    MAP_ADD(kAAFTypeID_OperationDefinitionStrongReference)
    MAP_ADD(kAAFTypeID_ParameterStrongReference)
    MAP_ADD(kAAFTypeID_ParameterDefinitionStrongReference)
    MAP_ADD(kAAFTypeID_PluginDefinitionStrongReference)
    MAP_ADD(kAAFTypeID_PropertyDefinitionStrongReference)
    MAP_ADD(kAAFTypeID_TaggedValueStrongReference)
    MAP_ADD(kAAFTypeID_TypeDefinitionStrongReference)
    MAP_ADD(kAAFTypeID_KLVDataStrongReference)
    MAP_ADD(kAAFTypeID_FileDescriptorStrongReference)
    MAP_ADD(kAAFTypeID_RIFFChunkStrongReference)
    MAP_ADD(kAAFTypeID_DescriptiveFrameworkStrongReference)
    MAP_ADD(kAAFTypeID_KLVDataDefinitionStrongReference)
    MAP_ADD(kAAFTypeID_TaggedValueDefinitionStrongReference)
    MAP_ADD(kAAFTypeID_DescriptiveObjectStrongReference)
    MAP_ADD(kAAFTypeID_DataDefinitionWeakReferenceSet)
    MAP_ADD(kAAFTypeID_ParameterDefinitionWeakReferenceSet)
    MAP_ADD(kAAFTypeID_PluginDefinitionWeakReferenceSet)
    MAP_ADD(kAAFTypeID_PropertyDefinitionWeakReferenceSet)
    MAP_ADD(kAAFTypeID_OperationDefinitionWeakReferenceVector)
    MAP_ADD(kAAFTypeID_TypeDefinitionWeakReferenceVector)
    MAP_ADD(kAAFTypeID_DataDefinitionWeakReferenceVector)
    MAP_ADD(kAAFTypeID_ClassDefinitionStrongReferenceSet)
    MAP_ADD(kAAFTypeID_CodecDefinitionStrongReferenceSet)
    MAP_ADD(kAAFTypeID_ContainerDefinitionStrongReferenceSet)
    MAP_ADD(kAAFTypeID_DataDefinitionStrongReferenceSet)
    MAP_ADD(kAAFTypeID_EssenceDataStrongReferenceSet)
    MAP_ADD(kAAFTypeID_InterpolationDefinitionStrongReferenceSet)
    MAP_ADD(kAAFTypeID_MobStrongReferenceSet)
    MAP_ADD(kAAFTypeID_OperationDefinitionStrongReferenceSet)
    MAP_ADD(kAAFTypeID_ParameterDefinitionStrongReferenceSet)
    MAP_ADD(kAAFTypeID_PluginDefinitionStrongReferenceSet)
    MAP_ADD(kAAFTypeID_PropertyDefinitionStrongReferenceSet)
    MAP_ADD(kAAFTypeID_TypeDefinitionStrongReferenceSet)
    MAP_ADD(kAAFTypeID_KLVDataDefinitionStrongReferenceSet)
    MAP_ADD(kAAFTypeID_TaggedValueDefinitionStrongReferenceSet)
    MAP_ADD(kAAFTypeID_DescriptiveObjectStrongReferenceSet)
    MAP_ADD(kAAFTypeID_ComponentStrongReferenceVector)
    MAP_ADD(kAAFTypeID_ControlPointStrongReferenceVector)
    MAP_ADD(kAAFTypeID_IdentificationStrongReferenceVector)
    MAP_ADD(kAAFTypeID_LocatorStrongReferenceVector)
    MAP_ADD(kAAFTypeID_MobSlotStrongReferenceVector)
    MAP_ADD(kAAFTypeID_SegmentStrongReferenceVector)
    MAP_ADD(kAAFTypeID_SourceReferenceStrongReferenceVector)
    MAP_ADD(kAAFTypeID_TaggedValueStrongReferenceVector)
    MAP_ADD(kAAFTypeID_KLVDataStrongReferenceVector)
    MAP_ADD(kAAFTypeID_ParameterStrongReferenceVector)
    MAP_ADD(kAAFTypeID_FileDescriptorStrongReferenceVector)
    MAP_ADD(kAAFTypeID_RIFFChunkStrongReferenceVector)
    MAP_ADD(kAAFTypeID_DescriptiveObjectStrongReferenceVector)
    #undef MAP_ADD

    return def_map;
}

std::map<std::string, aafUID_t> get_datadef_map()
{
    std::map<std::string, aafUID_t> def_map;
    #define MAP_ADD( NAME ) def_map[ #NAME ] = NAME;
    MAP_ADD(kAAFDataDef_Picture)
    MAP_ADD(kAAFDataDef_Picture)
    MAP_ADD(kAAFDataDef_LegacyPicture)
    MAP_ADD(kAAFDataDef_Matte)
    MAP_ADD(kAAFDataDef_PictureWithMatte)
    MAP_ADD(kAAFDataDef_Sound)
    MAP_ADD(kAAFDataDef_LegacySound)
    MAP_ADD(kAAFDataDef_Timecode)
    MAP_ADD(kAAFDataDef_LegacyTimecode)
    MAP_ADD(kAAFDataDef_Edgecode)
    MAP_ADD(kAAFDataDef_DescriptiveMetadata)
    MAP_ADD(kAAFDataDef_Auxiliary)
    MAP_ADD(kAAFDataDef_Unknown)
    #undef MAP_ADD

    return def_map;

}

std::map<std::string, aafUID_t> get_codecdef_map()
{
    std::map<std::string, aafUID_t> def_map;
    #define MAP_ADD( NAME ) def_map[ #NAME ] = NAME;
    MAP_ADD(kAAFCodecDef_None)
    MAP_ADD(kAAFCodecDef_PCM)
    MAP_ADD(kAAFCodecDef_WAVE)
    MAP_ADD(kAAFCodecDef_AIFC)
    MAP_ADD(kAAFCodecDef_JPEG)
    MAP_ADD(kAAFCodecDef_CDCI)
    MAP_ADD(kAAFCodecDef_RGBA)
    MAP_ADD(kAAFCodecDef_VC3)
    MAP_ADD(kAAFCodecDef_DNxHD)
    MAP_ADD(kAAFCodecFlavour_None)
    MAP_ADD(kAAFCodecFlavour_DV_Based_100Mbps_1080x50I)
    MAP_ADD(kAAFCodecFlavour_DV_Based_100Mbps_1080x5994I)
    MAP_ADD(kAAFCodecFlavour_DV_Based_100Mbps_720x50P)
    MAP_ADD(kAAFCodecFlavour_DV_Based_100Mbps_720x5994P)
    MAP_ADD(kAAFCodecFlavour_DV_Based_25Mbps_525_60)
    MAP_ADD(kAAFCodecFlavour_DV_Based_25Mbps_625_50)
    MAP_ADD(kAAFCodecFlavour_DV_Based_50Mbps_525_60)
    MAP_ADD(kAAFCodecFlavour_DV_Based_50Mbps_625_50)
    MAP_ADD(kAAFCodecFlavour_IEC_DV_525_60)
    MAP_ADD(kAAFCodecFlavour_IEC_DV_625_50)
    MAP_ADD(kAAFCodecFlavour_LegacyDV_525_60)
    MAP_ADD(kAAFCodecFlavour_LegacyDV_625_50)
    MAP_ADD(kAAFCodecFlavour_SMPTE_D10_50Mbps_625x50I)
    MAP_ADD(kAAFCodecFlavour_SMPTE_D10_50Mbps_525x5994I)
    MAP_ADD(kAAFCodecFlavour_SMPTE_D10_40Mbps_625x50I)
    MAP_ADD(kAAFCodecFlavour_SMPTE_D10_40Mbps_525x5994I)
    MAP_ADD(kAAFCodecFlavour_SMPTE_D10_30Mbps_625x50I)
    MAP_ADD(kAAFCodecFlavour_SMPTE_D10_30Mbps_525x5994I)
    MAP_ADD(kAAFCodecFlavour_VC3_1235)
    MAP_ADD(kAAFCodecFlavour_VC3_1237)
    MAP_ADD(kAAFCodecFlavour_VC3_1238)
    MAP_ADD(kAAFCodecFlavour_VC3_1241)
    MAP_ADD(kAAFCodecFlavour_VC3_1242)
    MAP_ADD(kAAFCodecFlavour_VC3_1243)
    MAP_ADD(kAAFCodecFlavour_VC3_1244)
    MAP_ADD(kAAFCodecFlavour_VC3_1250)
    MAP_ADD(kAAFCodecFlavour_VC3_1251)
    MAP_ADD(kAAFCodecFlavour_VC3_1252)
    MAP_ADD(kAAFCodecFlavour_VC3_1253)
    MAP_ADD(kAAFCodecFlavour_VC3_1254)
    #undef MAP_ADD

    return def_map;

}

std::map<std::string, aafUID_t> get_container_def_map()
{
    std::map<std::string, aafUID_t> def_map;
    #define MAP_ADD( NAME ) def_map[ #NAME ] = NAME;
    MAP_ADD(kAAFContainerDef_External)
    MAP_ADD(kAAFContainerDef_OMF)
    MAP_ADD(kAAFContainerDef_AAF)
    MAP_ADD(kAAFContainerDef_AAFMSS)
    MAP_ADD(kAAFContainerDef_AAFKLV)
    MAP_ADD(kAAFContainerDef_AAFXML)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_625x50I_50Mbps_DefinedTemplate)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_625x50I_50Mbps_ExtendedTemplate)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_625x50I_50Mbps_PictureOnly)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_525x5994I_50Mbps_DefinedTemplate)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_525x5994I_50Mbps_ExtendedTemplate)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_525x5994I_50Mbps_PictureOnly)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_625x50I_40Mbps_DefinedTemplate)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_625x50I_40Mbps_ExtendedTemplate)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_625x50I_40Mbps_PictureOnly)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_525x5994I_40Mbps_DefinedTemplate)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_525x5994I_40Mbps_ExtendedTemplate)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_525x5994I_40Mbps_PictureOnly)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_625x50I_30Mbps_DefinedTemplate)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_625x50I_30Mbps_ExtendedTemplate)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_625x50I_30Mbps_PictureOnly)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_525x5994I_30Mbps_DefinedTemplate)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_525x5994I_30Mbps_ExtendedTemplate)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_SMPTE_D10_525x5994I_30Mbps_PictureOnly)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_IECDV_525x5994I_25Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_IECDV_525x5994I_25Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_IECDV_625x50I_25Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_IECDV_625x50I_25Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_IECDV_525x5994I_25Mbps_SMPTE322M)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_IECDV_525x5994I_25Mbps_SMPTE322M)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_IECDV_625x50I_25Mbps_SMPTE322M)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_IECDV_625x50I_25Mbps_SMPTE322M)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_IECDV_UndefinedSource_25Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_IECDV_UndefinedSource_25Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_DVbased_525x5994I_25Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_DVbased_525x5994I_25Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_DVbased_625x50I_25Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_DVbased_625x50I_25Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_DVbased_525x5994I_50Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_DVbased_525x5994I_50Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_DVbased_625x50I_50Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_DVbased_625x50I_50Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_DVbased_1080x5994I_100Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_DVbased_1080x5994I_100Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_DVbased_1080x50I_100Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_DVbased_1080x50I_100Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_DVbased_720x5994P_100Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_DVbased_720x5994P_100Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_DVbased_720x50P_100Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_DVbased_720x50P_100Mbps)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_DVbased_UndefinedSource)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_DVbased_UndefinedSource)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_MPEGES_VideoStream0_SID)
    MAP_ADD(kAAFContainerDef_MXFGC_CustomClosedGOPwrapped_MPEGES_VideoStream1_SID)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_Uncompressed_525x5994I_720_422)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_Uncompressed_525x5994I_720_422)
    MAP_ADD(kAAFContainerDef_MXFGC_Linewrapped_Uncompressed_525x5994I_720_422)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_Uncompressed_625x50I_720_422)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_Uncompressed_625x50I_720_422)
    MAP_ADD(kAAFContainerDef_MXFGC_Linewrapped_Uncompressed_625x50I_720_422)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_Uncompressed_525x5994P_960_422)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_Uncompressed_525x5994P_960_422)
    MAP_ADD(kAAFContainerDef_MXFGC_Linewrapped_Uncompressed_525x5994P_960_422)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_Uncompressed_625x50P_960_422)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_Uncompressed_625x50P_960_422)
    MAP_ADD(kAAFContainerDef_MXFGC_Linewrapped_Uncompressed_625x50P_960_422)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_Broadcast_Wave_audio_data)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_Broadcast_Wave_audio_data)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_AES3_audio_data)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_AES3_audio_data)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_Alaw_Audio)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_Alaw_Audio)
    MAP_ADD(kAAFContainerDef_MXFGC_Customwrapped_Alaw_Audio)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_AVCbytestream_VideoStream0_SID)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_VC3)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_VC3)
    MAP_ADD(kAAFContainerDef_MXFGC_Framewrapped_VC1)
    MAP_ADD(kAAFContainerDef_MXFGC_Clipwrapped_VC1)
    MAP_ADD(kAAFContainerDef_MXFGC_Generic_Essence_Multiple_Mappings)
    MAP_ADD(kAAFContainerDef_RIFFWAVE)
    MAP_ADD(kAAFContainerDef_JFIF)
    MAP_ADD(kAAFContainerDef_AIFFAIFC)
    MAP_ADD(kAAFContainerDef_MXFGC_Avid_DNX_220X_1080p)
    MAP_ADD(kAAFContainerDef_MXFGC_Avid_DNX_145_1080p)
    MAP_ADD(kAAFContainerDef_MXFGC_Avid_DNX_220_1080p)
    MAP_ADD(kAAFContainerDef_MXFGC_Avid_DNX_36_1080p)
    MAP_ADD(kAAFContainerDef_MXFGC_Avid_DNX_220X_1080i)
    MAP_ADD(kAAFContainerDef_MXFGC_Avid_DNX_145_1080i)
    MAP_ADD(kAAFContainerDef_MXFGC_Avid_DNX_220_1080i)
    MAP_ADD(kAAFContainerDef_MXFGC_Avid_DNX_145_1440_1080i)
    MAP_ADD(kAAFContainerDef_MXFGC_Avid_DNX_220X_720p)
    MAP_ADD(kAAFContainerDef_MXFGC_Avid_DNX_220_720p)
    MAP_ADD(kAAFContainerDef_MXFGC_Avid_DNX_145_720p)
    #undef MAP_ADD

    return def_map;
}

std::map<std::string, aafUID_t> get_compressiondef_map()
{
    std::map<std::string, aafUID_t> def_map;
    #define MAP_ADD( NAME ) def_map[ #NAME ] = NAME;

    MAP_ADD(kAAFCompressionDef_AAF_CMPR_FULL_JPEG)
    MAP_ADD(kAAFCompressionDef_AAF_CMPR_AUNC422)
    MAP_ADD(kAAFCompressionDef_LegacyDV)
    MAP_ADD(kAAFCompressionDef_SMPTE_D10_50Mbps_625x50I)
    MAP_ADD(kAAFCompressionDef_SMPTE_D10_50Mbps_525x5994I)
    MAP_ADD(kAAFCompressionDef_SMPTE_D10_40Mbps_625x50I)
    MAP_ADD(kAAFCompressionDef_SMPTE_D10_40Mbps_525x5994I)
    MAP_ADD(kAAFCompressionDef_SMPTE_D10_30Mbps_625x50I)
    MAP_ADD(kAAFCompressionDef_SMPTE_D10_30Mbps_525x5994I)
    MAP_ADD(kAAFCompressionDef_IEC_DV_525_60)
    MAP_ADD(kAAFCompressionDef_IEC_DV_625_50)
    MAP_ADD(kAAFCompressionDef_DV_Based_25Mbps_525_60)
    MAP_ADD(kAAFCompressionDef_DV_Based_25Mbps_625_50)
    MAP_ADD(kAAFCompressionDef_DV_Based_50Mbps_525_60)
    MAP_ADD(kAAFCompressionDef_DV_Based_50Mbps_625_50)
    MAP_ADD(kAAFCompressionDef_DV_Based_100Mbps_1080x5994I)
    MAP_ADD(kAAFCompressionDef_DV_Based_100Mbps_1080x50I)
    MAP_ADD(kAAFCompressionDef_DV_Based_100Mbps_720x5994P)
    MAP_ADD(kAAFCompressionDef_DV_Based_100Mbps_720x50P)
    MAP_ADD(kAAFCompressionDef_VC3_1)
    MAP_ADD(kAAFCompressionDef_Avid_DNxHD_Legacy)
    #undef MAP_ADD
    return def_map;
}

std::map<std::string, aafUID_t> get_extenumdef_map()
{
    std::map<std::string, aafUID_t> def_map;
    #define MAP_ADD( NAME ) def_map[ #NAME ] = NAME;
    MAP_ADD(kAAFOperationCategory_Effect)
    MAP_ADD(kAAFTransferCharacteristic_ITU470_PAL)
    MAP_ADD(kAAFTransferCharacteristic_ITU709)
    MAP_ADD(kAAFTransferCharacteristic_SMPTE240M)
    MAP_ADD(kAAFTransferCharacteristic_274M_296M)
    MAP_ADD(kAAFTransferCharacteristic_ITU1361)
    MAP_ADD(kAAFTransferCharacteristic_linear)
    MAP_ADD(kAAFPluginCategory_Effect)
    MAP_ADD(kAAFPluginCategory_Codec)
    MAP_ADD(kAAFPluginCategory_Interpolation)
    MAP_ADD(kAAFUsage_SubClip)
    MAP_ADD(kAAFUsage_AdjustedClip)
    MAP_ADD(kAAFUsage_TopLevel)
    MAP_ADD(kAAFUsage_LowerLevel)
    MAP_ADD(kAAFUsage_Template)
    MAP_ADD(kAAFColorPrimaries_SMPTE170M)
    MAP_ADD(kAAFColorPrimaries_ITU470_PAL)
    MAP_ADD(kAAFColorPrimaries_ITU709)
    MAP_ADD(kAAFCodingEquations_ITU601)
    MAP_ADD(kAAFCodingEquations_ITU709)
    MAP_ADD(kAAFCodingEquations_SMPTE240M)
    #undef MAP_ADD
    return def_map;
}

std::map<std::string, aafUID_t> get_interpolationdef_map()
{
    std::map<std::string, aafUID_t> def_map;
    #define MAP_ADD( NAME ) def_map[ #NAME ] = NAME;
    MAP_ADD(kAAFInterpolationDef_None)
    MAP_ADD(kAAFInterpolationDef_Linear)
    MAP_ADD(kAAFInterpolationDef_Constant)
    MAP_ADD(kAAFInterpolationDef_BSpline)
    MAP_ADD(kAAFInterpolationDef_Log)
    MAP_ADD(kAAFInterpolationDef_Power)
    #undef MAP_ADD
    return def_map;
}

std::map<std::string, std::pair< aafUID_t, std::string > > get_essenceformats_def_map()
{
    std::map<std::string, std::pair< aafUID_t, std::string > > def_map;
    #define MAP_ADD( NAME, TYPE) def_map[ #NAME ] =  std::pair<aafUID_t, std::string >(NAME, #TYPE) ;
    MAP_ADD(kAAFCompression, operand.expAuid)
    MAP_ADD(kAAFPixelFormat, operand.expPixelFormat)
    MAP_ADD(kAAFFrameLayout, operand.expFrameLayout)
    MAP_ADD(kAAFFieldDominance, operand.expFieldDom)
    MAP_ADD(kAAFStoredRect, operand.expRect)
    MAP_ADD(kAAFDisplayRect, operand.expRect)
    MAP_ADD(kAAFSampledRect, operand.expRect)
    MAP_ADD(kAAFPixelSize, operand.expInt16)
    MAP_ADD(kAAFAspectRatio, operand.expRational)
    MAP_ADD(kAAFAlphaTransparency, operand.expInt32)
    MAP_ADD(kAAFGamma, operand.expRational)
    MAP_ADD(kAAFImageAlignmentFactor, operand.expInt32)
    MAP_ADD(kAAFVideoLineMap, operand.expLineMap)
    MAP_ADD(kAAFWillTransferLines, operand.expBoolean)
    MAP_ADD(kAAFIsCompressed, operand.expBoolean)
    MAP_ADD(kAAFLineLength, operand.expInt32)
    // exclusive to RGBA codec
    MAP_ADD(kAAFRGBCompLayout, operand.expCompArray)
    MAP_ADD(kAAFRGBCompSizes, operand.expCompSizeArray)
    MAP_ADD(kAAFRGBPalette, operand.expPointer)
    MAP_ADD(kAAFRGBPaletteLayout, operand.expCompArray)
    MAP_ADD(kAAFRGBPaletteSizes, operand.expCompSizeArray)
    //exclusive to CDCI codec
    MAP_ADD(kAAFCDCICompWidth, operand.expInt32)
    MAP_ADD(kAAFCDCIHorizSubsampling, operand.expUInt32)
    MAP_ADD(kAAFCDCIColorSiting, operand.expColorSiting)
    MAP_ADD(kAAFCDCIBlackLevel, operand.expUInt32)
    MAP_ADD(kAAFCDCIWhiteLevel, operand.expUInt32)
    MAP_ADD(kAAFCDCIColorRange, operand.expUInt32)
    MAP_ADD(kAAFCDCIPadBits, operand.expInt16)
    MAP_ADD(kAAFFieldStartOffset, ?operand.expUInt32)
    MAP_ADD(kAAFFieldEndOffset, ?operand.expUInt32)
    //Legacy
    MAP_ADD(kAAFLegacyCDCI, ?operand.expUInt32)
    MAP_ADD(kAAFResolutionID, operand.expUInt32)
    MAP_ADD(kAAFAudioSampleBits, operand.expInt32)
    MAP_ADD(kAAFMaxSampleBytes, ?operand.expUInt32)
    MAP_ADD(kAAFSampleRate, operand.expRational) //guess
    MAP_ADD(kAAFSampleFormat, ?operand.expUInt32)
    MAP_ADD(kAAFNumChannels, operand.expUInt32)
    MAP_ADD(kAAFPadBytesPerRow, ?operand.expUInt32)
    MAP_ADD(kAAFCompressionQuality, ?operand.expUInt32)
    MAP_ADD(kAAFLegacyAUIDs, ?operand.expUInt32)
    MAP_ADD(kAAFEssenceElementKey, ?operand.expUInt32)
    MAP_ADD(kAAFPhysicalTrackNum, ?operand.expUInt32)
    MAP_ADD(kAAFNumThreads, ?operand.expUInt32)
    MAP_ADD(kAAFBufferLayout, ?operand.expUInt32)

    #undef MAP_ADD

    return def_map;
}
